const translations = {
  es: {
    navFeatures: 'Características',
    navScreens: 'Pantallazos',
    navDownload: 'Descarga',
    navSupport: 'Soporte',
    heroTitle: 'Descubre lo mejor de tu ciudad junto a tus vecinos',
    heroSubtitle: 'Verifica tu identidad con ENS y comparte en los ZiPoints cercanos.',
    heroButton: 'Prueba la App',
    tagline: 'Social Must Be Local',
    featuresTitle: 'Características principales',
    feature1Title: 'Identidad verificada',
    feature1Desc: 'Tu dominio de Ethereum demuestra que eres una persona real, generando confianza.',
    feature2Title: 'Comunidades locales',
    feature2Desc: 'Los ZiPoints agrupan a quienes viven o trabajan cerca para conversar y recomendar.',
    feature3Title: 'Reputación',
    feature3Desc: 'Cada aporte suma reputación que desbloquea funciones y te permite validar a otros.',
    howTitle: '¿Cómo funciona?',
    how1: 'Inicia sesión con tu dominio de Ethereum Name Service para verificar tu identidad.',
    how2: 'Explora los ZiPoints de tu ciudad para descubrir comunidades cercanas.',
    how3: 'Comparte publicaciones, fotos y recomendaciones en los lugares que visites.',
    how4: 'Obtén reputación al interactuar: cada amistad, visita o nuevo ZiPoint suma puntos.',
    how5: 'Utiliza tu reputación para acceder a beneficios y ayudar a validar contenido de otros usuarios.',
    how6: 'Envía enlaces y contenido desde otras apps mediante la extensión de compartido de PostEth.',
    aboutTitle: '¿Por qué PostEth?',
    aboutP1: 'PostEth fusiona blockchain y geolocalización para conectar personas reales en un mismo barrio. En cada ZiPoint puedes publicar, chatear y ver historias efímeras.',
    aboutP2: 'Al iniciar sesión con ENS tus interacciones son seguras. La reputación obtenida te brinda más visibilidad y herramientas de moderación.',
    aboutP3: 'Comparte enlaces desde cualquier app con nuestra extensión y mantén activa la conversación. Únete hoy y vive tu comunidad de una forma nueva.',
    screensTitle: 'Pantallazos',
    downloadTitle: 'Descarga la aplicación',
    downloadSubtitle: 'Disponible para iOS. Próximamente para Android y web.',
    downloadButton: 'App Store',
    footerText: '© 2024 PostEth · ',
    privacyLink: 'Privacidad'
  },
  en: {
    navFeatures: 'Features',
    navScreens: 'Screens',
    navDownload: 'Download',
    navSupport: 'Support',
    heroTitle: 'Discover your city with real people',
    heroSubtitle: 'Verify with ENS and join the conversation at nearby ZiPoints.',
    heroButton: 'Try the App',
    tagline: 'Social Must Be Local',
    featuresTitle: 'Main Features',
    feature1Title: 'Verified identity',
    feature1Desc: 'Your Ethereum domain proves you are real, inspiring trust.',
    feature2Title: 'Local communities',
    feature2Desc: 'ZiPoints gather neighbours to chat, recommend and share experiences.',
    feature3Title: 'Reputation',
    feature3Desc: 'Every interaction builds reputation unlocking new abilities.',
    howTitle: 'How does it work?',
    how1: 'Log in with your ENS domain to verify your identity.',
    how2: 'Explore ZiPoints in your city to find nearby communities.',
    how3: 'Share posts, photos and recommendations wherever you go.',
    how4: 'Gain reputation through interactions: every friend or visit adds points.',
    how5: 'Use your reputation for perks and to help validate others.',
    how6: 'Send links and content from other apps via the PostEth share extension.',
    aboutTitle: 'Why PostEth?',
    aboutP1: 'PostEth mixes blockchain and location to connect local communities. Each ZiPoint is a timeline with chat and short-lived stories.',
    aboutP2: 'Logging in with ENS keeps interactions secure. Reputation gives you visibility and helps moderate content.',
    aboutP3: 'Share from any app using our extension and keep the conversation flowing. Join today to see your city in a new light.',
    screensTitle: 'Screenshots',
    downloadTitle: 'Download the app',
    downloadSubtitle: 'Available for iOS. Android and web coming soon!',
    downloadButton: 'App Store',
    footerText: '© 2024 PostEth · ',
    privacyLink: 'Privacy'
  },
  zh: {
    navFeatures: '特色',
    navScreens: '截图',
    navDownload: '下载',
    navSupport: '支持',
    heroTitle: '与社区分享并发现地点',
    heroSubtitle: '加入并使用以太坊域名服务验证身份。',
    heroButton: '试用应用',
    tagline: 'Social Must Be Local',
    featuresTitle: '主要功能',
    feature1Title: '已验证身份',
    feature1Desc: '使用以太坊名称登录，与真实用户互动。',
    feature2Title: '本地社区',
    feature2Desc: '在附近的ZiPoints发布内容并分享体验。',
    feature3Title: '声誉',
    feature3Desc: '通过贡献获得积分，解锁独家权益。',
    howTitle: '运作方式',
    how1: '使用ENS域名登录以验证身份。',
    how2: '探索城市中的ZiPoints，发现附近社区。',
    how3: '在访问的地点分享帖子、照片和推荐。',
    how4: '互动可提升声誉，每次访问都能获得积分。',
    how5: '利用声誉获取福利并帮助验证他人内容。',
    how6: '通过PostEth分享扩展从其他应用发送链接和内容。',
    aboutTitle: 'Why PostEth?',
    aboutP1: 'PostEth blends blockchain with geolocation to build real communities around you. Each ZiPoint is a hub where you can post, chat and view ephemeral stories.',
    aboutP2: 'Signing in with your Ethereum Name Service domain proves your identity. Every interaction earns reputation, helping you validate content and unlock perks.',
    aboutP3: 'Use the share extension to send links from other apps and keep the conversation going. Join today and remember: Social Must Be Local.',
    screensTitle: '截图',
    downloadTitle: '下载应用',
    downloadSubtitle: '适用于iOS，更多平台即将推出！',
    downloadButton: 'App Store',
    footerText: '© 2024 PostEth · ',
    privacyLink: '隐私'
  },
  hi: {
    navFeatures: 'विशेषताएँ',
    navScreens: 'स्क्रीनशॉट',
    navDownload: 'डाउनलोड',
    navSupport: 'सहायता',
    heroTitle: 'समुदाय के साथ स्थान साझा करें और खोजें',
    heroSubtitle: 'शामिल हों और Ethereum Name Service से अपनी पहचान सत्यापित करें।',
    heroButton: 'ऐप आज़माएं',
    tagline: 'Social Must Be Local',
    featuresTitle: 'मुख्य विशेषताएँ',
    feature1Title: 'सत्यापित पहचान',
    feature1Desc: 'अपने Ethereum नाम से साइन इन कर वास्तविक उपयोगकर्ताओं से जुड़ें।',
    feature2Title: 'स्थानीय समुदाय',
    feature2Desc: 'निकटस्थ ZiPoints पर पोस्ट करें और अनुभव साझा करें।',
    feature3Title: 'प्रतिष्ठा',
    feature3Desc: 'अपने योगदान से अंक अर्जित करें और विशेष लाभ पाएं।',
    howTitle: 'कैसे काम करता है?',
    how1: 'अपनी पहचान सत्यापित करने के लिए ENS डोमेन से लॉग इन करें।',
    how2: 'अपने शहर में ZiPoints खोजें और आस-पास के समुदाय पाएं।',
    how3: 'जहां भी जाएँ, पोस्ट, फ़ोटो और सिफारिशें साझा करें।',
    how4: 'हर इंटरैक्शन पर प्रतिष्ठा अर्जित करें; हर मित्रता या दौरा अंक देता है।',
    how5: 'प्रतिष्ठा का उपयोग लाभ पाने और दूसरों की सामग्री सत्यापित करने में करें।',
    how6: 'PostEth शेयर एक्सटेंशन से अन्य ऐप से लिंक और सामग्री भेजें।',
    aboutTitle: 'Why PostEth?',
    aboutP1: 'PostEth blends blockchain with geolocation to build real communities around you. Each ZiPoint is a hub where you can post, chat and view ephemeral stories.',
    aboutP2: 'Signing in with your Ethereum Name Service domain proves your identity. Every interaction earns reputation, helping you validate content and unlock perks.',
    aboutP3: 'Use the share extension to send links from other apps and keep the conversation going. Join today and remember: Social Must Be Local.',
    screensTitle: 'स्क्रीनशॉट',
    downloadTitle: 'ऐप डाउनलोड करें',
    downloadSubtitle: 'iOS के लिए उपलब्ध, जल्द ही अन्य प्लेटफॉर्म पर!',
    downloadButton: 'App Store',
    footerText: '© 2024 PostEth · ',
    privacyLink: 'गोपनीयता'
  },
  ar: {
    navFeatures: 'الميزات',
    navScreens: 'الصور',
    navDownload: 'تنزيل',
    navSupport: 'الدعم',
    heroTitle: 'شارك واكتشف الأماكن مع المجتمع',
    heroSubtitle: 'انضم وتحقق من هويتك عبر خدمة اسم Ethereum.',
    heroButton: 'جرّب التطبيق',
    tagline: 'Social Must Be Local',
    featuresTitle: 'الميزات الرئيسية',
    feature1Title: 'هوية موثّقة',
    feature1Desc: 'تواصل مع مستخدمين حقيقيين من خلال تسجيل الدخول باسم Ethereum الخاص بك.',
    feature2Title: 'مجتمعات محلية',
    feature2Desc: 'انشر في نقاط Zi القريبة وشارك تجاربك.',
    feature3Title: 'السمعة',
    feature3Desc: 'اكسب نقاطاً بمساهماتك واحصل على مزايا حصرية.',
    howTitle: 'كيف يعمل؟',
    how1: 'سجّل الدخول بنطاق ENS للتحقق من هويتك.',
    how2: 'استكشف نقاط Zi في مدينتك للعثور على مجتمعات قريبة.',
    how3: 'شارك المنشورات والصور والتوصيات في الأماكن التي تزورها.',
    how4: 'زد سمعتك من خلال التفاعل؛ كل زيارة تضيف نقاطاً.',
    how5: 'استخدم سمعتك للحصول على مزايا ولمساعدة الآخرين في التحقق من المحتوى.',
    how6: 'أرسل الروابط والمحتوى من التطبيقات الأخرى عبر إضافة المشاركة من PostEth.',
    aboutTitle: 'Why PostEth?',
    aboutP1: 'PostEth blends blockchain with geolocation to build real communities around you. Each ZiPoint is a hub where you can post, chat and view ephemeral stories.',
    aboutP2: 'Signing in with your Ethereum Name Service domain proves your identity. Every interaction earns reputation, helping you validate content and unlock perks.',
    aboutP3: 'Use the share extension to send links from other apps and keep the conversation going. Join today and remember: Social Must Be Local.',
    screensTitle: 'الصور',
    downloadTitle: 'حمّل التطبيق',
    downloadSubtitle: 'متوفر لنظام iOS. المزيد من المنصات قريباً!',
    downloadButton: 'App Store',
    footerText: '© 2024 PostEth · ',
    privacyLink: 'الخصوصية'
  },
  fr: {
    navFeatures: 'Fonctionnalités',
    navScreens: 'Captures',
    navDownload: 'Télécharger',
    navSupport: 'Support',
    heroTitle: 'Partagez et découvrez des lieux avec la communauté',
    heroSubtitle: 'Rejoignez-nous et vérifiez votre identité via Ethereum Name Service.',
    heroButton: 'Essayer l\'app',
    tagline: 'Social Must Be Local',
    featuresTitle: 'Fonctionnalités principales',
    feature1Title: 'Identité vérifiée',
    feature1Desc: 'Connectez-vous avec de vraies personnes grâce à votre nom Ethereum.',
    feature2Title: 'Communautés locales',
    feature2Desc: 'Publiez dans les ZiPoints proches et partagez des expériences uniques.',
    feature3Title: 'Réputation',
    feature3Desc: 'Gagnez des points avec vos contributions et débloquez des avantages.',
    howTitle: 'Comment ça marche ?',
    how1: 'Connectez votre domaine ENS pour vérifier votre identité.',
    how2: 'Explorez les ZiPoints de votre ville pour trouver des communautés proches.',
    how3: 'Partagez des publications, photos et recommandations partout où vous allez.',
    how4: 'Gagnez en réputation grâce à vos interactions : chaque visite rapporte.',
    how5: 'Utilisez votre réputation pour obtenir des avantages et aider à valider le contenu des autres.',
    how6: 'Envoyez des liens et du contenu depuis d\'autres apps via l\'extension de partage PostEth.',
    aboutTitle: 'Why PostEth?',
    aboutP1: 'PostEth blends blockchain with geolocation to build real communities around you. Each ZiPoint is a hub where you can post, chat and view ephemeral stories.',
    aboutP2: 'Signing in with your Ethereum Name Service domain proves your identity. Every interaction earns reputation, helping you validate content and unlock perks.',
    aboutP3: 'Use the share extension to send links from other apps and keep the conversation going. Join today and remember: Social Must Be Local.',
    screensTitle: 'Captures',
    downloadTitle: "Télécharger l'application", 
    downloadSubtitle: 'Disponible sur iOS. D\'autres plateformes arrivent bientôt !',
    downloadButton: 'App Store',
    footerText: '© 2024 PostEth · ',
    privacyLink: 'Confidentialité'
  },
  bn: {
    navFeatures: 'বৈশিষ্ট্য',
    navScreens: 'স্ক্রিনশট',
    navDownload: 'ডাউনলোড',
    navSupport: 'সহায়তা',
    heroTitle: 'সম্প্রদায়ের সাথে জায়গা শেয়ার করুন ও আবিষ্কার করুন',
    heroSubtitle: 'যোগ দিন এবং Ethereum Name Service দিয়ে পরিচয় নিশ্চিত করুন।',
    heroButton: 'অ্যাপ ব্যবহার করুন',
    tagline: 'Social Must Be Local',
    featuresTitle: 'মূল বৈশিষ্ট্য',
    feature1Title: 'যাচাইকৃত পরিচয়',
    feature1Desc: 'আপনার Ethereum নাম দিয়ে সাইন ইন করে বাস্তব ব্যবহারকারীদের সাথে যুক্ত হন।',
    feature2Title: 'স্থানীয় কমিউনিটি',
    feature2Desc: 'কাছের ZiPoints এ পোস্ট করুন এবং অভিজ্ঞতা শেয়ার করুন।',
    feature3Title: 'সুনাম',
    feature3Desc: 'অবদান দিয়ে পয়েন্ট অর্জন করুন এবং বিশেষ সুফল পান।',
    howTitle: 'কিভাবে কাজ করে?',
    how1: 'পরিচয় নিশ্চিত করতে আপনার ENS ডোমেইন দিয়ে লগইন করুন।',
    how2: 'আপনার শহরের ZiPoints ঘুরে কাছাকাছি কমিউনিটি আবিষ্কার করুন।',
    how3: 'আপনি যেখানেই যান পোস্ট, ছবি ও সুপারিশ শেয়ার করুন।',
    how4: 'প্রতিটি ইন্টারঅ্যাকশনে সুনাম বাড়ে; প্রতিটি ভিজিটে পয়েন্ট যোগ হয়।',
    how5: 'সুনাম ব্যবহার করে সুবিধা নিন এবং অন্যদের কন্টেন্ট যাচাইয়ে সাহায্য করুন।',
    how6: 'PostEth শেয়ার এক্সটেনশন দিয়ে অন্য অ্যাপ থেকে লিংক ও কন্টেন্ট পাঠান।',
    aboutTitle: 'Why PostEth?',
    aboutP1: 'PostEth blends blockchain with geolocation to build real communities around you. Each ZiPoint is a hub where you can post, chat and view ephemeral stories.',
    aboutP2: 'Signing in with your Ethereum Name Service domain proves your identity. Every interaction earns reputation, helping you validate content and unlock perks.',
    aboutP3: 'Use the share extension to send links from other apps and keep the conversation going. Join today and remember: Social Must Be Local.',
    screensTitle: 'স্ক্রিনশট',
    downloadTitle: 'অ্যাপ ডাউনলোড করুন',
    downloadSubtitle: 'iOS এ উপলব্ধ, শীঘ্রই আরও প্ল্যাটফর্মে!',
    downloadButton: 'App Store',
    footerText: '© 2024 PostEth · ',
    privacyLink: 'গোপনীয়তা'
  },
  ru: {
    navFeatures: 'Функции',
    navScreens: 'Скриншоты',
    navDownload: 'Скачать',
    navSupport: 'Поддержка',
    heroTitle: 'Делитесь и открывайте места вместе с сообществом',
    heroSubtitle: 'Присоединяйтесь и подтвердите личность через Ethereum Name Service.',
    heroButton: 'Попробовать приложение',
    tagline: 'Social Must Be Local',
    featuresTitle: 'Основные возможности',
    feature1Title: 'Проверенная личность',
    feature1Desc: 'Входите с именем Ethereum и общайтесь с реальными пользователями.',
    feature2Title: 'Местные сообщества',
    feature2Desc: 'Публикуйте рядом с вами в ZiPoints и делитесь впечатлениями.',
    feature3Title: 'Репутация',
    feature3Desc: 'Зарабатывайте очки за вклад и получайте преимущества.',
    howTitle: 'Как это работает?',
    how1: 'Войдите с доменом ENS, чтобы подтвердить личность.',
    how2: 'Ищите ZiPoints в своём городе для поиска сообществ поблизости.',
    how3: 'Делитесь постами, фото и рекомендациями в местах, которые посещаете.',
    how4: 'Получайте репутацию за взаимодействия: каждый визит добавляет очки.',
    how5: 'Используйте репутацию для бонусов и проверки контента других.',
    how6: 'Отправляйте ссылки и контент из других приложений через расширение PostEth.',
    aboutTitle: 'Why PostEth?',
    aboutP1: 'PostEth blends blockchain with geolocation to build real communities around you. Each ZiPoint is a hub where you can post, chat and view ephemeral stories.',
    aboutP2: 'Signing in with your Ethereum Name Service domain proves your identity. Every interaction earns reputation, helping you validate content and unlock perks.',
    aboutP3: 'Use the share extension to send links from other apps and keep the conversation going. Join today and remember: Social Must Be Local.',
    screensTitle: 'Скриншоты',
    downloadTitle: 'Скачать приложение',
    downloadSubtitle: 'Доступно для iOS. Скоро на других платформах!',
    downloadButton: 'App Store',
    footerText: '© 2024 PostEth · ',
    privacyLink: 'Конфиденциальность'
  },
  pt: {
    navFeatures: 'Recursos',
    navScreens: 'Capturas',
    navDownload: 'Baixar',
    navSupport: 'Suporte',
    heroTitle: 'Compartilhe e descubra lugares com a comunidade',
    heroSubtitle: 'Junte-se e verifique sua identidade com o Ethereum Name Service.',
    heroButton: 'Experimentar o App',
    tagline: 'Social Must Be Local',
    featuresTitle: 'Principais recursos',
    feature1Title: 'Identidade verificada',
    feature1Desc: 'Conecte-se com usuários reais usando seu nome Ethereum.',
    feature2Title: 'Comunidades locais',
    feature2Desc: 'Publique em ZiPoints próximos e compartilhe experiências.',
    feature3Title: 'Reputação',
    feature3Desc: 'Ganhe pontos com suas contribuições e obtenha benefícios exclusivos.',
    howTitle: 'Como funciona?',
    how1: 'Faça login com seu domínio ENS para verificar sua identidade.',
    how2: 'Explore ZiPoints na sua cidade para encontrar comunidades próximas.',
    how3: 'Compartilhe posts, fotos e recomendações por onde for.',
    how4: 'Ganhe reputação com interações: cada visita soma pontos.',
    how5: 'Use sua reputação para vantagens e para validar conteúdo de outros usuários.',
    how6: 'Envie links e conteúdo de outros apps com a extensão de compartilhamento do PostEth.',
    aboutTitle: 'Why PostEth?',
    aboutP1: 'PostEth blends blockchain with geolocation to build real communities around you. Each ZiPoint is a hub where you can post, chat and view ephemeral stories.',
    aboutP2: 'Signing in with your Ethereum Name Service domain proves your identity. Every interaction earns reputation, helping you validate content and unlock perks.',
    aboutP3: 'Use the share extension to send links from other apps and keep the conversation going. Join today and remember: Social Must Be Local.',
    screensTitle: 'Capturas',
    downloadTitle: 'Baixe o aplicativo',
    downloadSubtitle: 'Disponível para iOS. Em breve em mais plataformas!',
    downloadButton: 'App Store',
    footerText: '© 2024 PostEth · ',
    privacyLink: 'Privacidade'
  },
  de: {
    navFeatures: 'Funktionen',
    navScreens: 'Screenshots',
    navDownload: 'Download',
    navSupport: 'Support',
    heroTitle: 'Teile und entdecke Orte mit der Community',
    heroSubtitle: 'Tritt bei und verifiziere deine Identität mit dem Ethereum Name Service.',
    heroButton: 'App ausprobieren',
    tagline: 'Social Must Be Local',
    featuresTitle: 'Hauptfunktionen',
    feature1Title: 'Verifizierte Identität',
    feature1Desc: 'Melde dich mit deinem Ethereum-Namen an und verbinde dich mit echten Nutzern.',
    feature2Title: 'Lokale Communities',
    feature2Desc: 'Poste in nahegelegenen ZiPoints und teile besondere Erfahrungen.',
    feature3Title: 'Reputation',
    feature3Desc: 'Sammle Punkte durch Beiträge und erhalte exklusive Vorteile.',
    howTitle: 'Wie funktioniert es?',
    how1: 'Melde dich mit deiner ENS-Domain an, um deine Identität zu bestätigen.',
    how2: 'Erkunde ZiPoints in deiner Stadt und finde Communities in der Nähe.',
    how3: 'Teile Beiträge, Fotos und Empfehlungen an den Orten, die du besuchst.',
    how4: 'Erhalte Reputation durch Interaktionen: jeder Besuch bringt Punkte.',
    how5: 'Nutze deine Reputation, um Vorteile zu erhalten und anderen zu helfen.',
    how6: 'Sende Links und Inhalte aus anderen Apps über die PostEth-Share-Erweiterung.',
    aboutTitle: 'Why PostEth?',
    aboutP1: 'PostEth blends blockchain with geolocation to build real communities around you. Each ZiPoint is a hub where you can post, chat and view ephemeral stories.',
    aboutP2: 'Signing in with your Ethereum Name Service domain proves your identity. Every interaction earns reputation, helping you validate content and unlock perks.',
    aboutP3: 'Use the share extension to send links from other apps and keep the conversation going. Join today and remember: Social Must Be Local.',
    screensTitle: 'Screenshots',
    downloadTitle: 'App herunterladen',
    downloadSubtitle: 'Für iOS verfügbar, weitere Plattformen folgen!',
    downloadButton: 'App Store',
    footerText: '© 2024 PostEth · ',
    privacyLink: 'Datenschutz'
  }
};

const languages = {
  es: 'Español',
  en: 'English',
  zh: '中文',
  hi: 'हिन्दी',
  ar: 'العربية',
  fr: 'Français',
  bn: 'বাংলা',
  ru: 'Русский',
  pt: 'Português',
  de: 'Deutsch'
};

function applyTranslations(lang) {
  const t = translations[lang] || translations.es;
  for (const [key, value] of Object.entries(t)) {
    const el = document.getElementById(key);
    if (el) {
      if (key === 'privacyLink') {
        el.textContent = value;
      } else if (key === 'footerText') {
        el.firstChild && (el.firstChild.textContent = value);
      } else {
        el.textContent = value;
      }
    }
  }
  document.documentElement.lang = lang;
  document.getElementById('langSelect').value = lang;
}

document.addEventListener('DOMContentLoaded', () => {
  const select = document.getElementById('langSelect');
  for (const [code, name] of Object.entries(languages)) {
    const opt = document.createElement('option');
    opt.value = code;
    opt.textContent = name;
    select.appendChild(opt);
  }
  const defaultLang = document.documentElement.lang || 'es';
  applyTranslations(defaultLang);
  select.addEventListener('change', (e) => {
    applyTranslations(e.target.value);
  });
});
